# Snorkel Tutorial

Train a classifier to predict if comment data is spam or not spam.

https://snorkelproject.org/use-cases/01-spam-tutorial/

In [33]:
from utils import load_spam_dataset
from snorkel.labeling import labeling_function
from snorkel.labeling import PandasLFApplier
from snorkel.labeling import LFAnalysis
from snorkel.analysis import get_label_buckets
from snorkel.preprocess import preprocessor
from textblob import TextBlob
from snorkel.labeling import LabelingFunction
from snorkel.preprocess.nlp import SpacyPreprocessor
from snorkel.labeling.lf.nlp import nlp_labeling_function
from snorkel.labeling.model import MajorityLabelVoter
from snorkel.labeling.model import LabelModel
from snorkel.labeling import filter_unlabeled_dataframe
from sklearn.feature_extraction.text import CountVectorizer
from snorkel.utils import probs_to_preds
from sklearn.linear_model import LogisticRegression

import re

## 1. Load the Data

In [2]:
df_train, df_test = load_spam_dataset()

# Pull out labels for ease-of-use later
Y_test = df_test.label.values

In [3]:
# Define constants
ABSTAIN = -1
HAM = 0
SPAM = 1

## 2. Labeling Functions

**Examples (including, but not limited to):**
- Keyword searches: looking for specific words in a sentence
- Pattern matching: looking for specific syntactical patterns
- Third-party models: using an pre-trained model (usually a model for a different task than the one at hand)
- Distant supervision: using external knowledge base
- Crowdworker labels: treating each crowdworker as a black-box function that assigns labels to subsets of the data

In [4]:
# Look at 20 random data points from the train set to generate some ideas for LFs
df_train[["author", "text", "video"]].sample(20, random_state=2)

,author,text,video
4,ambareesh nimkar,"""eye of the tiger"" ""i am the champion"" seems l...",2
87,pratik patel,"mindblowing dance.,.,.superbbb song﻿",3
14,RaMpAgE420,Check out Berzerk video on my channel ! :D,4
80,Jason Haddad,"Hey, check out my new website!! This site is a...",1
104,austin green,Eminem is my insperasen and fav﻿,4
305,M.E.S,hey guys look im aware im spamming and it piss...,4
22,John Monster,Οh my god ... Roar is the most liked video at ...,2
338,Alanoud Alsaleh,I started hating Katy Perry after finding out ...,2
336,Leonardo Baptista,http://www.avaaz.org/po/petition/Youtube_Corpo...,1
143,UKz DoleSnacher,Remove This video its wank﻿,1
163,Monica Parker,Check out this video on YouTube:﻿,3
129,b0b1t.48058475,i rekt ur mum last nite. cuz da haterz were 2 ...,2
277,MeSoHornyMeLuvULongTime,This video is so racist!!! There are only anim...,2
265,HarveyIsTheBoss,You gotta say its funny. well not 2 billion wo...,1
214,janez novak,share and like this page to win a hand signed ...,4
76,Bizzle Sperq,https://www.facebook.com/nicushorbboy add mee ...,1
123,Gaming and Stuff PRO,"Hello! Do you like gaming, art videos, scienti...",1
268,Young IncoVEVO,Check out my Music Videos! and PLEASE SUBSCRIB...,1
433,Chris Edgar,Love the way you lie - Driveshaft﻿,4
40,rap classics,check out my channel for rap and hip hop music,4

In [5]:
@labeling_function()
def check(x):
    return SPAM if "check" in x.text.lower() else ABSTAIN


@labeling_function()
def check_out(x):
    return SPAM if "check out" in x.text.lower() else ABSTAIN

In [6]:
# Output of the apply() method is a label matrix which is a NumPy array L with one column for each LF and one row for each data point.
lfs = [check_out, check]

applier = PandasLFApplier(lfs=lfs)
L_train = applier.apply(df=df_train)

L_train

100%|██████████| 1586/1586 [00:00<00:00, 104246.32it/s]

array([[-1, -1],
       [-1, -1],
       [-1,  1],
       ...,
       [ 1,  1],
       [-1,  1],
       [ 1,  1]], shape=(1586, 2))

In [7]:
# Evaluate performance of the training set. The percentage of conclusive answers
coverage_check_out, coverage_check = (L_train != ABSTAIN).mean(axis=0)
print(f"check_out coverage: {coverage_check_out * 100:.1f}%")
print(f"check coverage: {coverage_check * 100:.1f}%")

check_out coverage: 21.4%
check coverage: 25.8%

- Polarity: The set of unique labels this LF outputs (excluding abstains)
- Coverage: The fraction of the dataset the LF labels
- Overlaps: The fraction of the dataset where this LF and at least one other LF label
- Conflicts: The fraction of the dataset where this LF and at least one other LF label and disagree
- Correct: The number of data points this LF labels correctly (if gold labels are provided)
- Incorrect: The number of data points this LF labels incorrectly (if gold labels are provided)
- Empirical Accuracy: The empirical accuracy of this LF (if gold labels are provided)

In [8]:
LFAnalysis(L=L_train, lfs=lfs).lf_summary()

/Users/ryanroche/repositories/tamu/fall26-code/685/weak-supervision/.venv/lib/python3.12/site-packages/snorkel/labeling/analysis.py:61: FutureWarning: Input has data type int64, but the output has been cast to float64.  In the future, the output data type will match the input. To avoid this warning, set the `dtype` parameter to `None` to have the output dtype match the input, or set it to the desired output data type.
  m = sparse.diags(np.ravel(self._L_sparse.max(axis=1).todense()))

           j Polarity  Coverage  Overlaps  Conflicts
check_out  0      [1]  0.214376  0.214376        0.0
check      1      [1]  0.257881  0.214376        0.0

In [9]:
# See if "check" function matches intuition
df_train.iloc[L_train[:, 1] == SPAM].sample(10, random_state=1)

,author,date,text,label,video
305,M.E.S,NaN,hey guys look im aware im spamming and it piss...,-1.0,4
265,Kawiana Lewis,2015-02-27T02:20:40.987000,Check out this video on YouTube:opponents mm <...,-1.0,3
89,Stricker Stric,NaN,eminem new song check out my videos,-1.0,4
147,TheGenieBoy,NaN,check out fantasy music right here -------&...,-1.0,4
240,Made2Falter,2014-09-09T23:55:30,"Check out our vids, our songs are awesome! And...",-1.0,2
273,Artady,2014-08-11T16:27:55,https://soundcloud.com/artady please check my ...,-1.0,2
94,Nick McGoldrick,2014-10-27T13:19:06,Check out my drum cover of E.T. here! thanks -...,-1.0,2
139,MFkin PRXPHETZ,2014-01-20T09:08:39,"if you like raw talent, raw lyrics, straight r...",-1.0,1
303,이 정훈,NaN,"This great Warning will happen soon. ,0\nLneaD...",-1.0,4
246,media.uploader,NaN,Check out my channel to see Rihanna short mix ...,-1.0,4

In [10]:
# Abstained due to small modifications of "check out"
buckets = get_label_buckets(L_train[:, 0], L_train[:, 1])
df_train.iloc[buckets[(ABSTAIN, SPAM)]].sample(10, random_state=1)

,author,date,text,label,video
403,ownpear902,2014-07-22T18:44:36.299000,check it out free stuff for watching videos an...,-1.0,3
256,PacKmaN,2014-11-05T21:56:39,check men out i put allot of effort into my mu...,-1.0,1
196,Angek95,2014-11-03T22:28:56,"Check my channel, please!﻿",-1.0,1
282,CronicleFPS,2014-11-06T03:10:26,Check me out I'm all about gaming ﻿,-1.0,1
352,MrJtill0317,NaN,┏━━━┓┏┓╋┏┓┏━━━┓┏━━━┓┏┓╋╋┏┓ ┃┏━┓┃┃┃╋┃┃┃┏━┓┃┗┓┏...,-1.0,4
161,MarianMusicChannel,2014-08-24T03:57:52,"Hello! I'm Marian, I'm a singer from Venezuela...",-1.0,2
270,Kyle Jaber,2014-01-19T00:21:29,Check me out! I'm kyle. I rap so yeah ﻿,-1.0,1
292,Soundhase,2014-08-19T18:59:38,Hi Guys! check this awesome EDM &amp; House mi...,-1.0,2
179,Nerdy Peach,2014-10-29T22:44:41,Hey! I'm NERDY PEACH and I'm a new youtuber an...,-1.0,2
16,zhichao wang,2013-11-29T02:13:56,i think about 100 millions of the views come f...,-1.0,1

In [11]:
# Try to get the best of both worlds
@labeling_function()
def regex_check_out(x):
    return SPAM if re.search(r"check.*out", x.text, flags=re.IGNORECASE) else ABSTAIN

lfs = [check_out, check, regex_check_out]

applier = PandasLFApplier(lfs=lfs)
L_train = applier.apply(df=df_train)

LFAnalysis(L=L_train, lfs=lfs).lf_summary()

100%|██████████| 1586/1586 [00:00<00:00, 70118.01it/s]
/Users/ryanroche/repositories/tamu/fall26-code/685/weak-supervision/.venv/lib/python3.12/site-packages/snorkel/labeling/analysis.py:61: FutureWarning: Input has data type int64, but the output has been cast to float64.  In the future, the output data type will match the input. To avoid this warning, set the `dtype` parameter to `None` to have the output dtype match the input, or set it to the desired output data type.
  m = sparse.diags(np.ravel(self._L_sparse.max(axis=1).todense()))

                 j Polarity  Coverage  Overlaps  Conflicts
check_out        0      [1]  0.214376  0.214376        0.0
check            1      [1]  0.257881  0.233922        0.0
regex_check_out  2      [1]  0.233922  0.233922        0.0

In [12]:
# To keep precision high (while not sacrificing much coverage), choose the regex-based rule
buckets = get_label_buckets(L_train[:, 1], L_train[:, 2])
df_train.iloc[buckets[(SPAM, ABSTAIN)]].sample(10, random_state=1)

,author,date,text,label,video
16,zhichao wang,2013-11-29T02:13:56,i think about 100 millions of the views come f...,-1.0,1
99,Santeri Saariokari,2014-09-03T16:32:59,"Hey guys go to check my video name ""growtopia ...",-1.0,2
21,BeBe Burkey,2013-11-28T16:30:13,and u should.d check my channel and tell me wh...,-1.0,1
239,Cony,2013-11-28T16:01:47,You should check my channel for Funny VIDEOS!!﻿,-1.0,1
288,Kochos,2014-01-20T17:08:37,i check back often to help reach 2x10^9 views ...,-1.0,1
65,by.Ovskiy,2014-10-13T17:09:46,"Rap from Belarus, check my channel:)﻿",-1.0,2
196,Angek95,2014-11-03T22:28:56,"Check my channel, please!﻿",-1.0,1
333,FreexGaming,2014-10-18T08:12:26,want to win borderlands the pre-sequel? check ...,-1.0,2
167,Brandon Pryor,2014-01-19T00:36:25,I dont even watch it anymore i just come here ...,-1.0,1
266,Zielimeek21,2013-11-28T21:49:00,I'm only checking the views﻿,-1.0,1

In [13]:
# EXAMPLE: Use third party model

@preprocessor(memoize=True)
def textblob_sentiment(x):
    scores = TextBlob(x.text)
    x.polarity = scores.sentiment.polarity
    x.subjectivity = scores.sentiment.subjectivity
    return x

@labeling_function(pre=[textblob_sentiment])
def textblob_polarity(x):
    return HAM if x.polarity > 0.9 else ABSTAIN

@labeling_function(pre=[textblob_sentiment])
def textblob_subjectivity(x):
    return HAM if x.subjectivity >= 0.5 else ABSTAIN

In [14]:
lfs = [textblob_polarity, textblob_subjectivity]

applier = PandasLFApplier(lfs)
L_train = applier.apply(df_train)

LFAnalysis(L_train, lfs).lf_summary()

100%|██████████| 1586/1586 [00:00<00:00, 5113.77it/s]
/Users/ryanroche/repositories/tamu/fall26-code/685/weak-supervision/.venv/lib/python3.12/site-packages/snorkel/labeling/analysis.py:61: FutureWarning: Input has data type int64, but the output has been cast to float64.  In the future, the output data type will match the input. To avoid this warning, set the `dtype` parameter to `None` to have the output dtype match the input, or set it to the desired output data type.
  m = sparse.diags(np.ravel(self._L_sparse.max(axis=1).todense()))

                       j Polarity  Coverage  Overlaps  Conflicts
textblob_polarity      0      [0]  0.035309  0.013871        0.0
textblob_subjectivity  1      [0]  0.357503  0.013871        0.0

## 3. More LFs

### a) Keyword LFs

In [15]:
def keyword_lookup(x, keywords, label):
    if any(word in x.text.lower() for word in keywords):
        return label
    return ABSTAIN


def make_keyword_lf(keywords, label=SPAM):
    return LabelingFunction(
        name=f"keyword_{keywords[0]}",
        f=keyword_lookup,
        resources=dict(keywords=keywords, label=label),
    )


"""Spam comments talk about 'my channel', 'my video', etc."""
keyword_my = make_keyword_lf(keywords=["my"])

"""Spam comments ask users to subscribe to their channels."""
keyword_subscribe = make_keyword_lf(keywords=["subscribe"])

"""Spam comments post links to other channels."""
keyword_link = make_keyword_lf(keywords=["http"])

"""Spam comments make requests rather than commenting."""
keyword_please = make_keyword_lf(keywords=["please", "plz"])

"""Ham comments actually talk about the video's content."""
keyword_song = make_keyword_lf(keywords=["song"], label=HAM)

### b) Pattern-matching LFs

Already implemented in `regex_check_out`

### c) Heuristic LFs

In [16]:
@labeling_function()
def short_comment(x):
    """Ham comments are often short, such as 'cool video!'"""
    return HAM if len(x.text.split()) < 5 else ABSTAIN

### d) LFs with complex preprocessors

In [17]:
spacy = SpacyPreprocessor(text_field="text", doc_field="doc", memoize=True)

In [18]:
@labeling_function(pre=[spacy])
def has_person(x):
    """Ham comments mention specific people and are short."""
    if len(x.doc) < 20 and any(ent.label_ == "PERSON" for ent in x.doc.ents):
        return HAM
    else:
        return ABSTAIN

In [19]:
# Another way to write the same function using prebuilt nlp function
@nlp_labeling_function()
def has_person_nlp(x):
    """Ham comments mention specific people and are short."""
    if len(x.doc) < 20 and any(ent.label_ == "PERSON" for ent in x.doc.ents):
        return HAM
    else:
        return ABSTAIN

### e) Third-party models

TextBlob implementation an example of this

## 4. Combining Labeling Function Outputs with the Label Model

In [20]:
lfs = [
    keyword_my,
    keyword_subscribe,
    keyword_link,
    keyword_please,
    keyword_song,
    regex_check_out,
    short_comment,
    has_person_nlp,
    textblob_polarity,
    textblob_subjectivity,
]

In [21]:
applier = PandasLFApplier(lfs=lfs)
L_train = applier.apply(df=df_train)
L_test = applier.apply(df=df_test)

LFAnalysis(L=L_train, lfs=lfs).lf_summary()

100%|██████████| 1586/1586 [00:04<00:00, 317.59it/s]
100%|██████████| 250/250 [00:00<00:00, 257.44it/s]
/Users/ryanroche/repositories/tamu/fall26-code/685/weak-supervision/.venv/lib/python3.12/site-packages/snorkel/labeling/analysis.py:61: FutureWarning: Input has data type int64, but the output has been cast to float64.  In the future, the output data type will match the input. To avoid this warning, set the `dtype` parameter to `None` to have the output dtype match the input, or set it to the desired output data type.
  m = sparse.diags(np.ravel(self._L_sparse.max(axis=1).todense()))

                       j Polarity  Coverage  Overlaps  Conflicts
keyword_my             0      [1]  0.198613  0.187894   0.112863
keyword_subscribe      1      [1]  0.127364  0.109079   0.069987
keyword_http           2      [1]  0.119168  0.100883   0.082598
keyword_please         3      [1]  0.112232  0.109710   0.058008
keyword_song           4      [0]  0.141866  0.112863   0.043506
regex_check_out        5      [1]  0.233922  0.132409   0.087011
short_comment          6      [0]  0.225725  0.151324   0.074401
has_person_nlp         7      [0]  0.129887  0.098361   0.043506
textblob_polarity      8      [0]  0.035309  0.032787   0.005044
textblob_subjectivity  9      [0]  0.357503  0.265448   0.160151

In [ ]:
# Convert the noisy LF outputs to a single noise-aware probabilistic (or confidence-weighted) label per data point

# Simple way
majority_model = MajorityLabelVoter()
preds_train = majority_model.predict(L=L_train)

preds_train

array([ 1,  1, -1, ...,  1,  1,  1], shape=(1586,))

In [29]:
# Instead use the LabelModel to combine the LF outputs
label_model = LabelModel(cardinality=2, verbose=True)   # cardinality = # of classes
label_model.fit(L_train=L_train, n_epochs=500, log_freq=100, seed=123)
probs_train = label_model.predict_proba(L=L_train)

INFO:root:Computing O...
INFO:root:Estimating \mu...
  0%|          | 0/500 [00:00<?, ?epoch/s]INFO:root:[0 epochs]: TRAIN:[loss=0.168]
INFO:root:[100 epochs]: TRAIN:[loss=0.011]
INFO:root:[200 epochs]: TRAIN:[loss=0.009]
INFO:root:[300 epochs]: TRAIN:[loss=0.008]
INFO:root:[400 epochs]: TRAIN:[loss=0.008]
100%|██████████| 500/500 [00:00<00:00, 5818.83epoch/s]
INFO:root:Finished Training

In [30]:
# Evaluate both methodologies
majority_acc = majority_model.score(L=L_test, Y=Y_test, tie_break_policy="random")[
    "accuracy"
]
print(f"{'Majority Vote Accuracy:':<25} {majority_acc * 100:.1f}%")

label_model_acc = label_model.score(L=L_test, Y=Y_test, tie_break_policy="random")[
    "accuracy"
]
print(f"{'Label Model Accuracy:':<25} {label_model_acc * 100:.1f}%")

Majority Vote Accuracy:   83.6%
Label Model Accuracy:     86.4%

In [31]:
# Filter out any data points that did not receive a label from any LF
df_train_filtered, probs_train_filtered = filter_unlabeled_dataframe(
    X=df_train, y=probs_train, L=L_train
)

## 5. Train the classifier

In [38]:
vectorizer = CountVectorizer(ngram_range=(1, 5))
X_train = vectorizer.fit_transform(df_train_filtered.text.tolist())
X_test = vectorizer.transform(df_test.text.tolist())

In [39]:
# To use a model that doesn't accept label distribution, use probs_to_preds to use the label of the class with the highest probability
preds_train_filtered = probs_to_preds(probs=probs_train_filtered)

In [40]:
sklearn_model = LogisticRegression(C=1e3, solver="liblinear")
sklearn_model.fit(X=X_train, y=preds_train_filtered)

LogisticRegression(C=1000.0, solver='liblinear')

In [41]:
print(f"Test Accuracy: {sklearn_model.score(X=X_test, y=Y_test) * 100:.1f}%")

Test Accuracy: 93.2%